name: Docker PR Build (x64)

on:
  pull_request:

jobs:
  docker-pr-build:
    runs-on: ubuntu-latest
    name: "Quick AMD64 build validation"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@7c525be6cc8a882d5163ce04293cac18617c709f

      - name: Build regular image (AMD64 only)
        uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47
        with:
          push: false
          context: "{{defaultContext}}"
          file: ./docker/Dockerfile
          platforms: linux/amd64
          tags: fdmmonster/fdm-monster:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
